#!/bin/bash
# wave-notes-setup uninstaller v1.0.0
# https://github.com/qbandev/wave-notes-setup

set -euo pipefail

VERSION="1.0.0"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default paths
DEFAULT_NOTES_DIR="$HOME/Documents/WaveNotes"
DEFAULT_BIN_DIR="$HOME/bin"
CONFIG_FILE="$HOME/.wave-notes.conf"

# Wave Terminal config path detection
detect_waveterm_config() {
    if [[ -d "$HOME/.config/waveterm" ]]; then
        echo "$HOME/.config/waveterm"
    elif [[ -d "$HOME/.waveterm" ]]; then
        echo "$HOME/.waveterm/config"
    else
        echo ""
    fi
}

WAVETERM_CONFIG=""

# Runtime variables
NOTES_DIR=""
BIN_DIR=""

print_header() {
    echo -e "${BLUE}🌊 wave-notes-setup uninstaller v$VERSION${NC}"
    echo "─────────────────────────────"
    echo ""
}

print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠️  Warning:${NC} $1"
}

print_error() {
    echo -e "${RED}[✗] Error:${NC} $1" >&2
}

load_config() {
    NOTES_DIR="$DEFAULT_NOTES_DIR"
    BIN_DIR="$DEFAULT_BIN_DIR"
    WAVETERM_CONFIG=$(detect_waveterm_config)

    if [[ -f "$CONFIG_FILE" ]]; then
        while IFS='=' read -r key value; do
            [[ "$key" =~ ^#.*$ ]] && continue
            [[ -z "$key" ]] && continue
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            value="${value//\$HOME/$HOME}"
            case "$key" in
                NOTES_DIR) NOTES_DIR="$value" ;;
                BIN_DIR) BIN_DIR="$value" ;;
            esac
        done < "$CONFIG_FILE"
    fi

    [[ -n "${WAVE_NOTES_DIR:-}" ]] && NOTES_DIR="$WAVE_NOTES_DIR"
    [[ -n "${WAVE_BIN_DIR:-}" ]] && BIN_DIR="$WAVE_BIN_DIR"

    NOTES_DIR="${NOTES_DIR/#\~/$HOME}"
    BIN_DIR="${BIN_DIR/#\~/$HOME}"
}

remove_widgets() {
    local widgets_file="$WAVETERM_CONFIG/widgets.json"

    if [[ ! -f "$widgets_file" ]]; then
        echo "No widgets.json found, skipping."
        return
    fi

    local temp_file
    temp_file=$(mktemp)

    if command -v jq >/dev/null 2>&1; then
        jq 'with_entries(select(.key | startswith("custom:notes-") | not))' "$widgets_file" > "$temp_file"
    else
        python3 -c "
import json
with open('$widgets_file', 'r') as f:
    data = json.load(f)
filtered = {k: v for k, v in data.items() if not k.startswith('custom:notes-')}
with open('$temp_file', 'w') as f:
    json.dump(filtered, f, indent=2)
"
    fi

    mv "$temp_file" "$widgets_file"
    print_success "Removed widgets from widgets.json"
}

remove_script() {
    local script_path="$BIN_DIR/wave-scratch.sh"

    if [[ ! -f "$script_path" ]]; then
        echo "No wave-scratch.sh found, skipping."
        return
    fi

    if grep -q "Generated by wave-notes-setup" "$script_path" 2>/dev/null; then
        rm "$script_path"
        print_success "Removed $script_path"
    else
        print_warning "Skipping $script_path (file modified or unknown origin)"
    fi
}

prompt_notes_deletion() {
    if [[ ! -d "$NOTES_DIR" ]]; then
        return
    fi

    echo ""
    read -p "Delete notes folder $NOTES_DIR? This will delete all your notes! (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$NOTES_DIR"
        print_success "Deleted $NOTES_DIR"
    else
        echo "Keeping notes folder at $NOTES_DIR"
    fi
}

prompt_config_deletion() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        return
    fi

    read -p "Delete config file $CONFIG_FILE? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm "$CONFIG_FILE"
        print_success "Deleted $CONFIG_FILE"
    else
        echo "Keeping config file."
    fi
}

main() {
    print_header

    echo "This will remove wave-notes-setup from your system."
    echo ""
    read -p "Continue? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    echo ""

    load_config
    remove_widgets
    remove_script
    prompt_notes_deletion
    prompt_config_deletion

    echo ""
    echo -e "${GREEN}✅ Uninstall complete!${NC}"
    echo "Restart Wave Terminal for changes to take effect."
}

main "$@"
